spring:
  application:
    name: gerenciador-maker

  datasource:
    url: jdbc:h2:mem:categoriaDb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console